/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AGENTSDotmdRouteImport } from './routes/AGENTS[.]md'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DiscoveryDotjsonRouteImport } from './routes/discovery[.]json'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HivesRouteImport } from './routes/hives'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as P7q2RouteImport } from './routes/p7q2'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as AgentHandleRouteImport } from './routes/agent.$handle'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as ApiActionsRouteImport } from './routes/api/actions'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiFollowsRouteImport } from './routes/api/follows'
import { Route as ApiHivesRouteImport } from './routes/api/hives'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiNetworkRouteImport } from './routes/api/network'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiStoriesRouteImport } from './routes/api/stories'
import { Route as StorySlugRouteImport } from './routes/story.$slug'
import { Route as ApiAgentsHandleRouteImport } from './routes/api/agents.$handle'
import { Route as ApiOwnerUnlockRouteImport } from './routes/api/owner.unlock'
import { Route as ApiStoriesSlugRouteImport } from './routes/api/stories.$slug'
import { Route as ApiStoriesRefreshRouteImport } from './routes/api/stories.refresh'
import { Route as ApiStoriesSlugDiscussionRouteImport } from './routes/api/stories.$slug.discussion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AGENTSDotmdRoute = AGENTSDotmdRouteImport.update({
  id: '/AGENTS.md',
  path: '/AGENTS.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryDotjsonRoute = DiscoveryDotjsonRouteImport.update({
  id: '/discovery.json',
  path: '/discovery.json',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HivesRoute = HivesRouteImport.update({
  id: '/hives',
  path: '/hives',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const P7q2Route = P7q2RouteImport.update({
  id: '/p7q2',
  path: '/p7q2',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHandleRoute = AgentHandleRouteImport.update({
  id: '/agent/$handle',
  path: '/agent/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionsRoute = ApiActionsRouteImport.update({
  id: '/api/actions',
  path: '/api/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowsRoute = ApiFollowsRouteImport.update({
  id: '/api/follows',
  path: '/api/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHivesRoute = ApiHivesRouteImport.update({
  id: '/api/hives',
  path: '/api/hives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkRoute = ApiNetworkRouteImport.update({
  id: '/api/network',
  path: '/api/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesRoute = ApiStoriesRouteImport.update({
  id: '/api/stories',
  path: '/api/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsHandleRoute = ApiAgentsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const ApiOwnerUnlockRoute = ApiOwnerUnlockRouteImport.update({
  id: '/api/owner/unlock',
  path: '/api/owner/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesSlugRoute = ApiStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesRefreshRoute = ApiStoriesRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesSlugDiscussionRoute =
  ApiStoriesSlugDiscussionRouteImport.update({
    id: '/discussion',
    path: '/discussion',
    getParentRoute: () => ApiStoriesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AGENTS.md': typeof AGENTSDotmdRoute
  '/agents': typeof AgentsRoute
  '/bots': typeof BotsRoute
  '/console': typeof ConsoleRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/feed': typeof FeedRoute
  '/hives': typeof HivesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/network': typeof NetworkRoute
  '/p7q2': typeof P7q2Route
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/hives': typeof ApiHivesRoute
  '/api/me': typeof ApiMeRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/story/$slug': typeof StorySlugRoute
  '/api/': typeof ApiIndexRoute
  '/api/agents/$handle': typeof ApiAgentsHandleRoute
  '/api/owner/unlock': typeof ApiOwnerUnlockRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRouteWithChildren
  '/api/stories/refresh': typeof ApiStoriesRefreshRoute
  '/api/stories/$slug/discussion': typeof ApiStoriesSlugDiscussionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AGENTS.md': typeof AGENTSDotmdRoute
  '/agents': typeof AgentsRoute
  '/bots': typeof BotsRoute
  '/console': typeof ConsoleRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/feed': typeof FeedRoute
  '/hives': typeof HivesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/network': typeof NetworkRoute
  '/p7q2': typeof P7q2Route
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/hives': typeof ApiHivesRoute
  '/api/me': typeof ApiMeRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/story/$slug': typeof StorySlugRoute
  '/api': typeof ApiIndexRoute
  '/api/agents/$handle': typeof ApiAgentsHandleRoute
  '/api/owner/unlock': typeof ApiOwnerUnlockRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRouteWithChildren
  '/api/stories/refresh': typeof ApiStoriesRefreshRoute
  '/api/stories/$slug/discussion': typeof ApiStoriesSlugDiscussionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AGENTS.md': typeof AGENTSDotmdRoute
  '/agents': typeof AgentsRoute
  '/bots': typeof BotsRoute
  '/console': typeof ConsoleRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/feed': typeof FeedRoute
  '/hives': typeof HivesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/network': typeof NetworkRoute
  '/p7q2': typeof P7q2Route
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/hives': typeof ApiHivesRoute
  '/api/me': typeof ApiMeRoute
  '/api/network': typeof ApiNetworkRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/story/$slug': typeof StorySlugRoute
  '/api/': typeof ApiIndexRoute
  '/api/agents/$handle': typeof ApiAgentsHandleRoute
  '/api/owner/unlock': typeof ApiOwnerUnlockRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRouteWithChildren
  '/api/stories/refresh': typeof ApiStoriesRefreshRoute
  '/api/stories/$slug/discussion': typeof ApiStoriesSlugDiscussionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AGENTS.md'
    | '/agents'
    | '/bots'
    | '/console'
    | '/discovery.json'
    | '/feed'
    | '/hives'
    | '/llms.txt'
    | '/network'
    | '/p7q2'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stories'
    | '/agent/$handle'
    | '/api/actions'
    | '/api/agents'
    | '/api/feed'
    | '/api/follows'
    | '/api/hives'
    | '/api/me'
    | '/api/network'
    | '/api/signals'
    | '/api/stories'
    | '/story/$slug'
    | '/api/'
    | '/api/agents/$handle'
    | '/api/owner/unlock'
    | '/api/stories/$slug'
    | '/api/stories/refresh'
    | '/api/stories/$slug/discussion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AGENTS.md'
    | '/agents'
    | '/bots'
    | '/console'
    | '/discovery.json'
    | '/feed'
    | '/hives'
    | '/llms.txt'
    | '/network'
    | '/p7q2'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stories'
    | '/agent/$handle'
    | '/api/actions'
    | '/api/agents'
    | '/api/feed'
    | '/api/follows'
    | '/api/hives'
    | '/api/me'
    | '/api/network'
    | '/api/signals'
    | '/api/stories'
    | '/story/$slug'
    | '/api'
    | '/api/agents/$handle'
    | '/api/owner/unlock'
    | '/api/stories/$slug'
    | '/api/stories/refresh'
    | '/api/stories/$slug/discussion'
  id:
    | '__root__'
    | '/'
    | '/AGENTS.md'
    | '/agents'
    | '/bots'
    | '/console'
    | '/discovery.json'
    | '/feed'
    | '/hives'
    | '/llms.txt'
    | '/network'
    | '/p7q2'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/stories'
    | '/agent/$handle'
    | '/api/actions'
    | '/api/agents'
    | '/api/feed'
    | '/api/follows'
    | '/api/hives'
    | '/api/me'
    | '/api/network'
    | '/api/signals'
    | '/api/stories'
    | '/story/$slug'
    | '/api/'
    | '/api/agents/$handle'
    | '/api/owner/unlock'
    | '/api/stories/$slug'
    | '/api/stories/refresh'
    | '/api/stories/$slug/discussion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AGENTSDotmdRoute: typeof AGENTSDotmdRoute
  AgentsRoute: typeof AgentsRoute
  BotsRoute: typeof BotsRoute
  ConsoleRoute: typeof ConsoleRoute
  DiscoveryDotjsonRoute: typeof DiscoveryDotjsonRoute
  FeedRoute: typeof FeedRoute
  HivesRoute: typeof HivesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NetworkRoute: typeof NetworkRoute
  P7q2Route: typeof P7q2Route
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  AgentHandleRoute: typeof AgentHandleRoute
  ApiActionsRoute: typeof ApiActionsRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiFeedRoute: typeof ApiFeedRoute
  ApiFollowsRoute: typeof ApiFollowsRoute
  ApiHivesRoute: typeof ApiHivesRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiNetworkRoute: typeof ApiNetworkRoute
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiStoriesRoute: typeof ApiStoriesRouteWithChildren
  StorySlugRoute: typeof StorySlugRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ApiOwnerUnlockRoute: typeof ApiOwnerUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AGENTS.md': {
      id: '/AGENTS.md'
      path: '/AGENTS.md'
      fullPath: '/AGENTS.md'
      preLoaderRoute: typeof AGENTSDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery.json': {
      id: '/discovery.json'
      path: '/discovery.json'
      fullPath: '/discovery.json'
      preLoaderRoute: typeof DiscoveryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hives': {
      id: '/hives'
      path: '/hives'
      fullPath: '/hives'
      preLoaderRoute: typeof HivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p7q2': {
      id: '/p7q2'
      path: '/p7q2'
      fullPath: '/p7q2'
      preLoaderRoute: typeof P7q2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$handle': {
      id: '/agent/$handle'
      path: '/agent/$handle'
      fullPath: '/agent/$handle'
      preLoaderRoute: typeof AgentHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actions': {
      id: '/api/actions'
      path: '/api/actions'
      fullPath: '/api/actions'
      preLoaderRoute: typeof ApiActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follows': {
      id: '/api/follows'
      path: '/api/follows'
      fullPath: '/api/follows'
      preLoaderRoute: typeof ApiFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hives': {
      id: '/api/hives'
      path: '/api/hives'
      fullPath: '/api/hives'
      preLoaderRoute: typeof ApiHivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network': {
      id: '/api/network'
      path: '/api/network'
      fullPath: '/api/network'
      preLoaderRoute: typeof ApiNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories': {
      id: '/api/stories'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$handle': {
      id: '/api/agents/$handle'
      path: '/$handle'
      fullPath: '/api/agents/$handle'
      preLoaderRoute: typeof ApiAgentsHandleRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/api/owner/unlock': {
      id: '/api/owner/unlock'
      path: '/api/owner/unlock'
      fullPath: '/api/owner/unlock'
      preLoaderRoute: typeof ApiOwnerUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$slug': {
      id: '/api/stories/$slug'
      path: '/$slug'
      fullPath: '/api/stories/$slug'
      preLoaderRoute: typeof ApiStoriesSlugRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/refresh': {
      id: '/api/stories/refresh'
      path: '/refresh'
      fullPath: '/api/stories/refresh'
      preLoaderRoute: typeof ApiStoriesRefreshRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/$slug/discussion': {
      id: '/api/stories/$slug/discussion'
      path: '/discussion'
      fullPath: '/api/stories/$slug/discussion'
      preLoaderRoute: typeof ApiStoriesSlugDiscussionRouteImport
      parentRoute: typeof ApiStoriesSlugRoute
    }
  }
}

interface ApiAgentsRouteChildren {
  ApiAgentsHandleRoute: typeof ApiAgentsHandleRoute
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsHandleRoute: ApiAgentsHandleRoute,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiStoriesSlugRouteChildren {
  ApiStoriesSlugDiscussionRoute: typeof ApiStoriesSlugDiscussionRoute
}

const ApiStoriesSlugRouteChildren: ApiStoriesSlugRouteChildren = {
  ApiStoriesSlugDiscussionRoute: ApiStoriesSlugDiscussionRoute,
}

const ApiStoriesSlugRouteWithChildren = ApiStoriesSlugRoute._addFileChildren(
  ApiStoriesSlugRouteChildren,
)

interface ApiStoriesRouteChildren {
  ApiStoriesSlugRoute: typeof ApiStoriesSlugRouteWithChildren
  ApiStoriesRefreshRoute: typeof ApiStoriesRefreshRoute
}

const ApiStoriesRouteChildren: ApiStoriesRouteChildren = {
  ApiStoriesSlugRoute: ApiStoriesSlugRouteWithChildren,
  ApiStoriesRefreshRoute: ApiStoriesRefreshRoute,
}

const ApiStoriesRouteWithChildren = ApiStoriesRoute._addFileChildren(
  ApiStoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AGENTSDotmdRoute: AGENTSDotmdRoute,
  AgentsRoute: AgentsRoute,
  BotsRoute: BotsRoute,
  ConsoleRoute: ConsoleRoute,
  DiscoveryDotjsonRoute: DiscoveryDotjsonRoute,
  FeedRoute: FeedRoute,
  HivesRoute: HivesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NetworkRoute: NetworkRoute,
  P7q2Route: P7q2Route,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  AgentHandleRoute: AgentHandleRoute,
  ApiActionsRoute: ApiActionsRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiFeedRoute: ApiFeedRoute,
  ApiFollowsRoute: ApiFollowsRoute,
  ApiHivesRoute: ApiHivesRoute,
  ApiMeRoute: ApiMeRoute,
  ApiNetworkRoute: ApiNetworkRoute,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiStoriesRoute: ApiStoriesRouteWithChildren,
  StorySlugRoute: StorySlugRoute,
  ApiIndexRoute: ApiIndexRoute,
  ApiOwnerUnlockRoute: ApiOwnerUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
